<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Register button clicked successfully]]>
    </line>
    <line>
      <![CDATA[PII Verification page displayed successfully]]>
    </line>
    <line>
      <![CDATA[PII Verification done successfully]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="83986" started-at="2018-12-11T12:47:39Z" finished-at="2018-12-11T12:49:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="83986" started-at="2018-12-11T12:47:39Z" finished-at="2018-12-11T12:49:03Z">
      <class name="executableClass.Fully_Enrolled_Customers_Flow">
        <test-method status="FAIL" signature="TC012_EnrollinNewProgram_G_AND_G_cardNumber_VerifybyPII()[pri:4, instance:executableClass.Fully_Enrolled_Customers_Flow@271053e1]" name="TC012_EnrollinNewProgram_G_AND_G_cardNumber_VerifybyPII" duration-ms="83953" started-at="2018-12-11T18:17:39Z" finished-at="2018-12-11T18:19:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error in contactinfo page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error in contactinfo page
	at org.testng.Assert.fail(Assert.java:94)
	at computedClass.Computed_FullyEnrollment_Flow.ContactInfoPage(Computed_FullyEnrollment_Flow.java:292)
	at executableClass.Fully_Enrolled_Customers_Flow.TC012_EnrollinNewProgram_G_AND_G_cardNumber_VerifybyPII(Fully_Enrolled_Customers_Flow.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:150)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Register button clicked successfully]]>
            </line>
            <line>
              <![CDATA[PII Verification page displayed successfully]]>
            </line>
            <line>
              <![CDATA[PII Verification done successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC012_EnrollinNewProgram_G_AND_G_cardNumber_VerifybyPII -->
      </class> <!-- executableClass.Fully_Enrolled_Customers_Flow -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
